AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Tracing: Active

Parameters:
  DbUrl:
    Type: String
    Description: JDBC URL for the RDS database
  DbUser:
    Type: String
    Description: Username for the RDS database
  DbPassword:
    Type: String
    Description: Password for the RDS database
    NoEcho: true

Resources:
  RoleCompleteDynamoDbAccess:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonDynamoDBFullAccess

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Staging

  ProtectedApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Staging
      Auth:
        DefaultAuthorizer: MyLambdaTokenAuthorizer
        Authorizers:
          MyLambdaTokenAuthorizer:
            FunctionPayloadType: TOKEN
            FunctionArn: !GetAtt AuthorizerFunction.Arn

  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./auth-app/ABCAuth
      Handler: com.abc.inc.auth.Authorizer::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./login-service/ABCLoginService
      Handler: com.abc.inc.login.App::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          RDB_HOST: ""
          RDB_PORT: ""
          RDB_USERNAME: ""
          RDB_PASSWORD: ""
      Events:
        ProductService:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /login
            Method: POST

  ProductServiceApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./product-service-api/ABCProductServiceAPI
      Handler: com.abc.inc.psa.App::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          DYNAMO_LOCAL_URL: ""
      Role: !GetAtt RoleCompleteDynamoDbAccess.Arn
      Events:
        ProductService:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /restaurants
            Method: GET

  ProductCrudApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./product-crud-api/ABCProductCrudAPI
      Handler: com.abc.inc.pca.App::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          DYNAMO_LOCAL_URL: ""
          RDB_HOST: ""
          RDB_PORT: ""
          RDB_USERNAME: ""
          RDB_PASSWORD: ""
      Role: !GetAtt RoleCompleteDynamoDbAccess.Arn
      Events:
        ProductService:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ProtectedApiGateway
            Path: /restaurants/crud/{proxy+}
            Method: ANY

  CartFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./cart-service/ABCCartService
      Handler: com.abc.inc.cart.App::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          DYNAMO_LOCAL_URL: ""
      Role: !GetAtt RoleCompleteDynamoDbAccess.Arn
      Events:
        CartService:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ProtectedApiGateway
            Path: /cart/{proxy+}
            Method: ANY

  OrderPlacementFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./order-placement-service/OrderPlacementService
      Handler: com.abc.inc.orderplacement.App::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          DYNAMO_LOCAL_URL: ""
      Role: !GetAtt RoleCompleteDynamoDbAccess.Arn
      Events:
        OrderPlacementService:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref ProtectedApiGateway
            Path: /order-placement/{proxy+}
            Method: ANY

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL for Stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com"
